-- name: CreateUser :one
INSERT INTO USERS(USERNAME, EMAIL, PASSWORD)
VALUES ($1, $2, $3)
RETURNING ID, USERNAME, EMAIL, CREATED_AT, UPDATED_AT;

-- name: GetUser :one
SELECT ID, USERNAME, EMAIL, CREATED_AT, UPDATED_AT FROM USERS WHERE ID = $1;

-- name: ListUsers :many
SELECT ID, USERNAME, EMAIL, CREATED_AT, UPDATED_AT FROM USERS ORDER BY ID LIMIT $1 OFFSET $2;

-- name: CreateBlog :one
INSERT INTO BLOGS(TITLE, CONTENT,USER_ID)
VALUES ($1, $2, $3)
RETURNING ID, TITLE, CONTENT, USER_ID, CREATED_AT, UPDATED_AT;

-- name: ListBlogs :many
SELECT ID, TITLE, CONTENT, USER_ID, CREATED_AT, UPDATED_AT FROM BLOGS ORDER BY ID;

-- name: GetUserByUsername :one
SELECT ID, USERNAME, EMAIL, PASSWORD, CREATED_AT, UPDATED_AT FROM USERS WHERE USERNAME = $1;

-- name: GetUserByEmail :one
SELECT ID, USERNAME, EMAIL, PASSWORD, CREATED_AT, UPDATED_AT FROM USERS WHERE EMAIL = $1;

-- name: CreateUserProfile :one
INSERT INTO USER_PROFILES (USER_ID, PROFILE_IMAGE)
VALUES ($1, $2)
RETURNING ID, USER_ID, PROFILE_IMAGE;

-- name: GetUserProfileByUserId :one
SELECT ID, USER_ID, PROFILE_IMAGE, CREATED_AT, UPDATED_AT
FROM USER_PROFILES WHERE USER_ID = $1;
