-- name: CreateUser :one
INSERT INTO USERS(USERNAME, EMAIL, PASSWORD)
VALUES ($1, $2, $3)
RETURNING ID, USERNAME, EMAIL, CREATED_AT, UPDATED_AT;

-- name: GetUser :one
SELECT ID, USERNAME, EMAIL, CREATED_AT, UPDATED_AT FROM USERS WHERE ID = $1;

-- name: ListUsers :many
SELECT ID, USERNAME, EMAIL, CREATED_AT, UPDATED_AT FROM USERS ORDER BY ID;

-- name: CreateBlog :one
INSERT INTO BLOGS(TITLE, CONTENT,USER_ID)
VALUES ($1, $2, $3)
RETURNING ID, TITLE, CONTENT, USER_ID, CREATED_AT, UPDATED_AT;

-- name: ListBlogs :many
SELECT ID, TITLE, CONTENT, USER_ID, CREATED_AT, UPDATED_AT FROM BLOGS ORDER BY ID;
