// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBlogStmt, err = db.PrepareContext(ctx, createBlog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBlog: %w", err)
	}
	if q.createOTPStmt, err = db.PrepareContext(ctx, createOTP); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOTP: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserProfileStmt, err = db.PrepareContext(ctx, createUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserProfile: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.getUserProfileByUserIdStmt, err = db.PrepareContext(ctx, getUserProfileByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserProfileByUserId: %w", err)
	}
	if q.getValidOtpForUserStmt, err = db.PrepareContext(ctx, getValidOtpForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetValidOtpForUser: %w", err)
	}
	if q.listBlogsStmt, err = db.PrepareContext(ctx, listBlogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListBlogs: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.markOtpUsedStmt, err = db.PrepareContext(ctx, markOtpUsed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkOtpUsed: %w", err)
	}
	if q.markUserEmailVerifiedStmt, err = db.PrepareContext(ctx, markUserEmailVerified); err != nil {
		return nil, fmt.Errorf("error preparing query MarkUserEmailVerified: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBlogStmt != nil {
		if cerr := q.createBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBlogStmt: %w", cerr)
		}
	}
	if q.createOTPStmt != nil {
		if cerr := q.createOTPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOTPStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserProfileStmt != nil {
		if cerr := q.createUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserProfileStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.getUserProfileByUserIdStmt != nil {
		if cerr := q.getUserProfileByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserProfileByUserIdStmt: %w", cerr)
		}
	}
	if q.getValidOtpForUserStmt != nil {
		if cerr := q.getValidOtpForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getValidOtpForUserStmt: %w", cerr)
		}
	}
	if q.listBlogsStmt != nil {
		if cerr := q.listBlogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBlogsStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.markOtpUsedStmt != nil {
		if cerr := q.markOtpUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markOtpUsedStmt: %w", cerr)
		}
	}
	if q.markUserEmailVerifiedStmt != nil {
		if cerr := q.markUserEmailVerifiedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markUserEmailVerifiedStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	createBlogStmt             *sql.Stmt
	createOTPStmt              *sql.Stmt
	createUserStmt             *sql.Stmt
	createUserProfileStmt      *sql.Stmt
	getUserStmt                *sql.Stmt
	getUserByEmailStmt         *sql.Stmt
	getUserByUsernameStmt      *sql.Stmt
	getUserProfileByUserIdStmt *sql.Stmt
	getValidOtpForUserStmt     *sql.Stmt
	listBlogsStmt              *sql.Stmt
	listUsersStmt              *sql.Stmt
	markOtpUsedStmt            *sql.Stmt
	markUserEmailVerifiedStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		createBlogStmt:             q.createBlogStmt,
		createOTPStmt:              q.createOTPStmt,
		createUserStmt:             q.createUserStmt,
		createUserProfileStmt:      q.createUserProfileStmt,
		getUserStmt:                q.getUserStmt,
		getUserByEmailStmt:         q.getUserByEmailStmt,
		getUserByUsernameStmt:      q.getUserByUsernameStmt,
		getUserProfileByUserIdStmt: q.getUserProfileByUserIdStmt,
		getValidOtpForUserStmt:     q.getValidOtpForUserStmt,
		listBlogsStmt:              q.listBlogsStmt,
		listUsersStmt:              q.listUsersStmt,
		markOtpUsedStmt:            q.markOtpUsedStmt,
		markUserEmailVerifiedStmt:  q.markUserEmailVerifiedStmt,
	}
}
