// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Blog struct {
	ID        int32        `json:"id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	UserID    int32        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type OtpVerification struct {
	ID        int32        `json:"id"`
	OtpKey    string       `json:"otp_key"`
	UserID    int32        `json:"user_id"`
	IssuedAt  sql.NullTime `json:"issued_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	IsUsed    sql.NullBool `json:"is_used"`
}

type User struct {
	ID            int32        `json:"id"`
	Username      string       `json:"username"`
	Email         string       `json:"email"`
	Password      string       `json:"password"`
	EmailVerified sql.NullBool `json:"email_verified"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type UserProfile struct {
	ID           int32          `json:"id"`
	UserID       int32          `json:"user_id"`
	ProfileImage sql.NullString `json:"profile_image"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
