// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO BLOGS(TITLE, CONTENT,USER_ID)
VALUES ($1, $2, $3)
RETURNING ID, TITLE, CONTENT, USER_ID, CREATED_AT, UPDATED_AT
`

type CreateBlogParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  int32  `json:"user_id"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.createBlogStmt, createBlog, arg.Title, arg.Content, arg.UserID)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO OTP_VERIFICATION (OTP_KEY, USER_ID)
VALUES ($1, $2)
RETURNING ID, OTP_KEY, ISSUED_AT, EXPIRES_AT, USER_ID
`

type CreateOTPParams struct {
	OtpKey string `json:"otp_key"`
	UserID int32  `json:"user_id"`
}

type CreateOTPRow struct {
	ID        int32        `json:"id"`
	OtpKey    string       `json:"otp_key"`
	IssuedAt  sql.NullTime `json:"issued_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	UserID    int32        `json:"user_id"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (CreateOTPRow, error) {
	row := q.queryRow(ctx, q.createOTPStmt, createOTP, arg.OtpKey, arg.UserID)
	var i CreateOTPRow
	err := row.Scan(
		&i.ID,
		&i.OtpKey,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO USERS(USERNAME, EMAIL, PASSWORD)
VALUES ($1, $2, $3)
RETURNING ID, USERNAME, EMAIL, EMAIL_VERIFIED, CREATED_AT, UPDATED_AT
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID            int32        `json:"id"`
	Username      string       `json:"username"`
	Email         string       `json:"email"`
	EmailVerified sql.NullBool `json:"email_verified"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO USER_PROFILES (USER_ID, PROFILE_IMAGE)
VALUES ($1, $2)
RETURNING ID, USER_ID, PROFILE_IMAGE
`

type CreateUserProfileParams struct {
	UserID       int32          `json:"user_id"`
	ProfileImage sql.NullString `json:"profile_image"`
}

type CreateUserProfileRow struct {
	ID           int32          `json:"id"`
	UserID       int32          `json:"user_id"`
	ProfileImage sql.NullString `json:"profile_image"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (CreateUserProfileRow, error) {
	row := q.queryRow(ctx, q.createUserProfileStmt, createUserProfile, arg.UserID, arg.ProfileImage)
	var i CreateUserProfileRow
	err := row.Scan(&i.ID, &i.UserID, &i.ProfileImage)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT ID, USERNAME, EMAIL, EMAIL_VERIFIED, CREATED_AT, UPDATED_AT FROM USERS WHERE ID = $1
`

type GetUserRow struct {
	ID            int32        `json:"id"`
	Username      string       `json:"username"`
	Email         string       `json:"email"`
	EmailVerified sql.NullBool `json:"email_verified"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT ID, USERNAME, EMAIL, PASSWORD, EMAIL_VERIFIED, CREATED_AT, UPDATED_AT FROM USERS WHERE EMAIL = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT ID, USERNAME, EMAIL, PASSWORD, EMAIL_VERIFIED, CREATED_AT, UPDATED_AT FROM USERS WHERE USERNAME = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserId = `-- name: GetUserProfileByUserId :one
SELECT ID, USER_ID, PROFILE_IMAGE, CREATED_AT, UPDATED_AT
FROM USER_PROFILES WHERE USER_ID = $1
`

func (q *Queries) GetUserProfileByUserId(ctx context.Context, userID int32) (UserProfile, error) {
	row := q.queryRow(ctx, q.getUserProfileByUserIdStmt, getUserProfileByUserId, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidOtpForUser = `-- name: GetValidOtpForUser :one
SELECT id, otp_key, user_id, issued_at, expires_at, is_used FROM otp_verification WHERE user_id = $1 AND is_used = false AND expires_at > now() ORDER BY issued_at DESC LIMIT 1 FOR UPDATE
`

func (q *Queries) GetValidOtpForUser(ctx context.Context, userID int32) (OtpVerification, error) {
	row := q.queryRow(ctx, q.getValidOtpForUserStmt, getValidOtpForUser, userID)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.OtpKey,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.IsUsed,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT ID, TITLE, CONTENT, USER_ID, CREATED_AT, UPDATED_AT FROM BLOGS ORDER BY ID
`

func (q *Queries) ListBlogs(ctx context.Context) ([]Blog, error) {
	rows, err := q.query(ctx, q.listBlogsStmt, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT ID, USERNAME, EMAIL, EMAIL_VERIFIED, CREATED_AT, UPDATED_AT FROM USERS ORDER BY ID LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID            int32        `json:"id"`
	Username      string       `json:"username"`
	Email         string       `json:"email"`
	EmailVerified sql.NullBool `json:"email_verified"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOtpUsed = `-- name: MarkOtpUsed :one
UPDATE otp_verification
SET is_used = true
WHERE id = $1
AND is_used = false
AND expires_at > now()
RETURNING id, otp_key, issued_at, expires_at, user_id
`

type MarkOtpUsedRow struct {
	ID        int32        `json:"id"`
	OtpKey    string       `json:"otp_key"`
	IssuedAt  sql.NullTime `json:"issued_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	UserID    int32        `json:"user_id"`
}

func (q *Queries) MarkOtpUsed(ctx context.Context, id int32) (MarkOtpUsedRow, error) {
	row := q.queryRow(ctx, q.markOtpUsedStmt, markOtpUsed, id)
	var i MarkOtpUsedRow
	err := row.Scan(
		&i.ID,
		&i.OtpKey,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE users
SET email_verified = true,
    updated_at = now()
WHERE id = $1
AND email_verified = false
RETURNING id, username, email, email_verified, created_at, updated_at
`

type MarkUserEmailVerifiedRow struct {
	ID            int32        `json:"id"`
	Username      string       `json:"username"`
	Email         string       `json:"email"`
	EmailVerified sql.NullBool `json:"email_verified"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id int32) (MarkUserEmailVerifiedRow, error) {
	row := q.queryRow(ctx, q.markUserEmailVerifiedStmt, markUserEmailVerified, id)
	var i MarkUserEmailVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
